site_url: "https://localhost:4321/"
# site_url: "https://ies-abastos-erasmus.netlify.app/"
# display_url: "https://localhost:4321/"
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# Ubicación donde se almacenarán los archivos en el repositorio
media_folder: "src/assets/images/uploads"
# El atributo src para los medios cargados
public_folder: "src/assets/images/uploads"
locale: es

collections:
  - name: "ka1" # Usado en rutas, por ejemplo, /admin/collections/blog
    # slug: "{{year}}-{{month}}-{{day}}_{{slug}}" # Archivos en la carpeta de documentos tendrán un nombre similar a 2020-01-07-my-post.md
    label: "KA1" # Usado en la interfaz de usuario de /admin
    folder: "/src/pages/posts/ka1" # La ruta a la carpeta donde se almacenan los documentos
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_filters:
      - { label: "KA1", field: tags, pattern: "KA1" }
      - { label: "KA2", field: tags, pattern: "KA2" }
      - { label: "KA3", field: tags, pattern: "KA3" }
      - { label: "FP", field: tags, pattern: "FP" }
      - { label: "Escolar", field: tags, pattern: "Escolar" }
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "/src/layouts/MarkdownPostLayout.astro",
        }
        # añadir slug

      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "pubDate", widget: "datetime" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - {
          label: "Descripción de la imagen",
          name: "image_alt",
          widget: "string",
        }
      - {
          label: "Categoría",
          name: "tags",
          widget: "select",
          multiple: true,
          min: 1,
          max: 2,
          options: ["Escolar", "FP", "Educación Superior"],
          default: ["FP"],
          # - { label: "Escolar", value: "0" }
          # - { label: "FP", value: "1" }
          # - { label: "Educación Superior", value: "2" }
        }
      - { label: "Cuerpo del Post", name: "body", widget: "markdown" }
      # - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      # - {
      #     label: "Categorías",
      #     name: "tags",
      #     widget: "list",
      #     label_singular: "Añadir categoría",
      #     field: { label: Categoría, name: tag, widget: string },
      #   }
