# site_url: "http://localhost:4321/"
site_url: 'https://ies-abastos-erasmus.netlify.app/'
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# Ubicación donde se almacenarán los archivos en el repositorio
media_folder: '/public/assets/images/'
# El atributo src para los medios cargados
public_folder: '/assets/images/'
locale: es
collections:
  - name: 'categories' # Usado en rutas, por ejemplo, /admin/collections/blog
    slug: '{{type}}_{{slug}}' # Archivos en la carpeta de documentos tendrán un nombre similar a ka1_my-category.md
    label: 'Categorías' # Usado en la interfaz de usuario de /admin
    label_singular: 'Categoría' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/categories' # La ruta a la carpeta donde se almacenan los documentos
    identifier_field: name
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por proyecto
      - { label: 'Tipo', field: type }
    summary: '{{type | label}}: {{name}}'
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - { label: 'Nombre', name: 'name', widget: 'string' }
      - {
          label: 'Tipo de Categoría',
          name: 'type',
          widget: 'select',
          options:
            [
              { label: 'Proyecto', value: 'project' },
              { label: 'Etiqueta', value: 'tag' },
            ],
          hint: 'Tipo de proyecto como KA1 o KA2 y etiqueta como FP o Escolar',
        }
      - {
          label: 'Cuerpo de la categoría',
          name: 'body',
          widget: 'markdown',
          hint: 'Escribe el contenido de la categoría',
        }

  - name: 'projects' # Usado en rutas, por ejemplo, /admin/collections/blog
    # slug: '{{slug}}_{{type}}_{{tag}}' # Archivos en la carpeta de documentos tendrán un nombre similar a 'proyecto_tipo_tag'
    label: 'Proyectos' # Usado en la interfaz de usuario de /admin
    label_singular: 'Proyecto' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/projects' # La ruta a la carpeta donde se almacenan los documentos
    identifier_field: title
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por tipo de proyecto y etiqueta
      - { label: 'Tipo de Proyecto', field: type }
      - { label: 'Etiqueta', field: tag }
    summary: "{{title}} - {{type}} - {{tag}} - {{author}} - {{date | date('DD-MM-YYYY')}}"
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: 'Autor',
          name: 'author',
          widget: 'string',
          default: 'IES Abastos Erasmus+',
        }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de Inicio', name: 'date', widget: 'datetime' }
      - {
          label: 'Imagen',
          name: 'images',
          widget: 'image',
          allow_multiple: true,
          required: false,
          hint: 'Imagenes destacadas del proyecto. Recomendable optimizarlas antes de subirlas.',
        }
      - {
          label: 'Video URL',
          name: 'videoUrl',
          widget: 'string',
          required: false,
          hint: 'URL de un video subido previamente a Google Drive',
        }
      - {
          label: 'Tipo de Proyecto',
          name: 'type',
          widget: 'relation',
          collection: 'categories',
          value_field: '{{slug}}',
          search_fields: ['name'],
          display_fields: ['name'],
          filters: [{ field: 'type', values: ['project'] }],
          # multiple: true,
          # min: 1,
          # max: 2,
          hint: 'Selecciona un tipo de proyecto. Por ejemplo, KA1 o KA2',
        }
      - {
          label: 'Etiqueta del Proyecto',
          name: 'tag',
          widget: 'relation',
          collection: 'categories',
          value_field: '{{slug}}',
          search_fields: ['name'],
          display_fields: ['name'],
          filters: [{ field: 'type', values: ['tag'] }],
          # multiple: true,
          # min: 1,
          # max: 2,
          hint: 'Selecciona un etiqueta para el proyecto. Por ejemplo, FP o Escolar',
        }
      - {
          label: 'En curso',
          name: 'inProgress',
          widget: 'boolean',
          default: 'true',
          hint: 'Indica si el proyecto está en curso o finalizado',
        }
      - {
          label: 'Cuerpo del Proyecto',
          name: 'body',
          widget: 'markdown',
          hint: 'Escribe el contenido del proyecto',
        }

  - name: 'posts' # Usado en rutas, por ejemplo, /admin/collections/blog
    slug: '{{year}}-{{month}}-{{day}}_{{project}}_{{author}}_{{slug}}' # Archivos en la carpeta de documentos tendrán un nombre similar a 2020-01-07_autor_my-post.md
    label: 'Posts' # Usado en la interfaz de usuario de /admin
    label_singular: 'Post' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/posts' # La ruta a la carpeta donde se almacenan los documentos
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por proyecto
      - { label: 'Project', field: project }
    summary: "{{title}} - {{project}} - {{author}} - {{pubDate | date('DD-MM-YYYY')}}"
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: 'Autor',
          name: 'author',
          widget: 'string',
          default: 'IES Abastos Erasmus+',
        }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Fecha de Publicación', name: 'pubDate', widget: 'datetime' }
      - {
          label: 'Proyecto Relacionado',
          name: 'project',
          widget: 'relation',
          collection: 'projects',
          value_field: '{{ slug }}',
          search_fields: ['title', 'author', 'type', 'tag'],
          display_fields: ['title', 'author', 'type', 'tag'],
          hint: 'Puedes buscar por título, autor, tipo o etiqueta del proyecto relacionado.',
        }
      - {
          label: 'Imagen',
          name: 'images',
          widget: 'image',
          required: false,
          hint: 'Imagen destacada del post. Recomendable optimizarla antes de subirla.',
        }
      - {
          label: 'Video URL',
          name: 'videoUrl',
          widget: 'string',
          required: false,
          hint: 'URL de un video de YouTube o Google Drive',
        }
      - {
          label: 'Cuerpo del Post',
          name: 'body',
          widget: 'markdown',
          hint: 'Escribe el contenido del post',
        }

  # - name: "authors" # Usado en rutas, por ejemplo, /admin/collections/blog
  #   slug: "{{name}}" # Archivos en la carpeta de documentos tendrán un nombre similar a autorName_authorLastName.md
  #   label: "Autores" # Usado en la interfaz de usuario de /admin
  #   label_singular: "Autor" # Usado en la interfaz de usuario de /admin
  #   folder: "/src/content/authors" # La ruta a la carpeta donde se almacenan los documentos
  #   # identifier_field: "name"
  #   create: true # Permitir a los usuarios crear nuevos documentos en esta colección
  #   view_groups: # Agrupar documentos por proyecto
  #     - { label: "Tipo", field: type }
  #   summary: "{{name}}"
  #   fields: # Los campos para cada documento, generalmente en el frontmatter
  #     - {
  #         label: "Layout",
  #         name: "layout",
  #         widget: "hidden",
  #         default: "/src/layouts/AuthorLayout.astro",
  #       }
  #     - { label: "Nombre Completo", name: "name", widget: "string" }
