# site_url: "http://localhost:4321/"
site_url: 'https://ies-abastos-erasmus.netlify.app/'
backend:
  name: git-gateway
  branch: main # Rama a actualizar (opcional; por defecto es master)
# Ubicación donde se almacenarán los archivos en el repositorio
media_folder: '/public/assets/images/uploads'
# El atributo src para los medios cargados
public_folder: '/assets/images/uploads'
i18n:
  # Requerido y puede ser uno de multiple_folders, multiple_files o single_file
  # multiple_folders - guarda los archivos en `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - guarda los archivos en `<folder>/<slug>.<locale>.<extension>`
  # single_file - guarda un solo archivo en `<folder>/<slug>.<extension>`
  structure: multiple_folders
  # Requerido - una lista de locales para mostrar en la interfaz de edición
  locales: [es, en]
  # Opcional, por defecto es el primer elemento en locales.
  # El locale que se utilizará para la validación de campos y como referencia para la entrada.
  default_locale: es
collections:
  - name: 'categories' # Usado en rutas, por ejemplo, /admin/collections/categories
    slug: '{{type}}_{{slug}}' # Archivos en la carpeta de documentos tendrán un nombre similar a ka1_my-category.md
    label: 'Categorías' # Usado en la interfaz de usuario de /admin
    label_singular: 'Categoría' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/categories' # La ruta a la carpeta donde se almacenan los documentos
    # identifier_field: title
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por proyecto
      - { label: 'Tipo', field: type }
    summary: '{{type | label}}: {{title}}'
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - { label: 'Nombre', name: 'title', widget: 'string' }
      - {
          label: 'Nombre en ingles',
          name: 'englishTitle',
          widget: 'string',
          required: false,
          hint: 'Nombre de la categoría en inglés, si es necesario',
        }
      - {
          label: 'Tipo de Categoría',
          name: 'type',
          widget: 'select',
          options:
            [
              { label: 'Proyecto', value: 'project' },
              { label: 'Sector', value: 'sector' },
            ],
          hint: 'Tipo de proyecto como KA1 o KA2 y sector como FP o Escolar',
        }
      # - {
      #     label: 'Cuerpo de la categoría',
      #     name: 'body',
      #     widget: 'markdown',
      #     required: false,
      #     hint: 'Escribe el contenido de la categoría',
      #   }

  - name: 'projects' # Usado en rutas, por ejemplo, /admin/collections/projects
    slug: '{{slug}}' # Archivos en la carpeta de documentos tendrán un nombre similar a 'proyecto_tipo_sector'
    label: 'Proyectos' # Usado en la interfaz de usuario de /admin
    label_singular: 'Proyecto' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/projects' # La ruta a la carpeta donde se almacenan los documentos
    # identifier_field: title
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por tipo de proyecto y etiqueta
      - { label: 'Tipo de Proyecto', field: type }
      - { label: 'Etiqueta', field: sector }
    summary: "{{title}} - {{type}} - {{sector}} - {{author}} - {{date | date('DD-MM-YYYY')}}"
    # locales: [es, en]
    # default_locale: es
    i18n: true
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: 'Autor',
          name: 'author',
          widget: 'string',
          default: 'IES Abastos',
          i18n: duplicate,
        }
      - { label: 'Titulo', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Descripción',
          name: 'description',
          widget: 'string',
          i18n: true,
        }
      - {
          label: 'Fecha de Inicio',
          name: 'date',
          widget: 'datetime',
          i18n: duplicate,
        }
      - {
          label: 'Web del Proyecto',
          name: 'web',
          widget: 'string',
          required: true,
          hint: 'URL de la web oficial del proyecto',
          i18n: duplicate,
        }
      - {
          label: 'Imagen',
          name: 'images',
          widget: 'image',
          required: false,
          hint: 'Imagenes destacadas del proyecto. Recomendable optimizarlas antes de subirlas si no es por URL.',
          i18n: duplicate,
        }
      - {
          label: 'Video URL',
          name: 'videoUrl',
          widget: 'string',
          required: false,
          hint: 'URL de un video subido previamente a Google Drive',
          i18n: duplicate,
        }
      - {
          label: 'Tipo de Proyecto',
          name: 'type',
          widget: 'relation',
          collection: 'categories',
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
          filters: [{ field: 'type', values: ['project'] }],
          hint: 'Selecciona un tipo de proyecto. Por ejemplo, KA1 o KA2',
          i18n: duplicate,
        }
      - {
          label: 'Sector del Proyecto',
          name: 'sector',
          widget: 'relation',
          collection: 'categories',
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
          filters: [{ field: 'type', values: ['sector'] }],
          hint: 'Selecciona un sector para el proyecto. Por ejemplo, FP o Escolar',
          i18n: duplicate,
        }
      - {
          label: 'En curso',
          name: 'inProgress',
          widget: 'boolean',
          default: true,
          hint: 'Indica si el proyecto está en curso o finalizado',
          i18n: duplicate,
        }
      - {
          label: 'Cuerpo del Proyecto',
          name: 'body',
          widget: 'markdown',
          hint: 'Escribe el contenido del proyecto',
          i18n: true,
        }

  - name: 'posts' # Usado en rutas, por ejemplo, /admin/collections/blog
    slug: '{{year}}-{{month}}-{{day}}_{{project}}_{{author}}_{{slug}}' # Archivos en la carpeta de documentos tendrán un nombre similar a 2020-01-07_autor_my-post.md
    label: 'Posts' # Usado en la interfaz de usuario de /admin
    label_singular: 'Post' # Usado en la interfaz de usuario de /admin
    folder: '/src/content/posts' # La ruta a la carpeta donde se almacenan los documentos
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    view_groups: # Agrupar documentos por proyecto
      - { label: 'Project', field: project }
    summary: "{{title}} - {{project}} - {{author}} - {{date | date('DD-MM-YYYY')}}"
    i18n: true
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: 'Autor',
          name: 'author',
          widget: 'string',
          default: 'IES Abastos',
          i18n: duplicate,
        }
      - { label: 'Titulo', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Descripción',
          name: 'description',
          widget: 'string',
          i18n: true,
        }
      - {
          label: 'Fecha de Publicación',
          name: 'date',
          widget: 'datetime',
          i18n: duplicate,
        }
      - {
          label: 'Proyecto Relacionado',
          name: 'project',
          widget: 'relation',
          collection: 'projects',
          value_field: '{{slug}}',
          search_fields: ['title', 'type', 'sector', 'author'],
          display_fields: ['title', 'type', 'sector', 'author'],
          hint: 'Puedes buscar por título, autor, tipo o sector del proyecto relacionado.',
          i18n: duplicate,
        }
      - {
          label: 'Imagen',
          name: 'images',
          widget: 'image',
          required: false,
          choose_url: false,
          media_library: { config: { multiple: true } },
          hint: 'Imágenes destacadas de la publicación. Recomendable optimizarlas antes de subirlas.',
          i18n: duplicate,
        }
      - {
          label: 'Imágenes URL (Links)',
          name: 'imageUrls',
          widget: 'string',
          required: false,
          hint: 'Imagenes que vienen de links de Internet. Se pueden escribir varias URL separadas por comas sin espacios adyacentes. Ejemplo: https://example.com/image1.jpg,https://example.com/image2.jpg',
          i18n: duplicate,
        }
      - {
          label: 'Video URL (Link)',
          name: 'videoUrl',
          widget: 'string',
          required: false,
          hint: 'URL de un video de YouTube o Google Drive',
          i18n: duplicate,
        }
      - {
          label: 'Cuerpo del Post',
          name: 'body',
          widget: 'markdown',
          hint: 'Escribe el contenido del post',
          i18n: true,
        }

  # - name: "authors" # Usado en rutas, por ejemplo, /admin/collections/blog
  #   slug: "{{name}}" # Archivos en la carpeta de documentos tendrán un nombre similar a autorName_authorLastName.md
  #   label: "Autores" # Usado en la interfaz de usuario de /admin
  #   label_singular: "Autor" # Usado en la interfaz de usuario de /admin
  #   folder: "/src/content/authors" # La ruta a la carpeta donde se almacenan los documentos
  #   # identifier_field: "name"
  #   create: true # Permitir a los usuarios crear nuevos documentos en esta colección
  #   view_groups: # Agrupar documentos por proyecto
  #     - { label: "Tipo", field: type }
  #   summary: "{{name}}"
  #   fields: # Los campos para cada documento, generalmente en el frontmatter
  #     - {
  #         label: "Layout",
  #         name: "layout",
  #         widget: "hidden",
  #         default: "/src/layouts/AuthorLayout.astro",
  #       }
  #     - { label: "Nombre Completo", name: "name", widget: "string" }
