backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "src/assets/images/uploads" # Ubicación donde se almacenarán los archivos en el repositorio
public_folder: "src/assets/images/uploads" # El atributo src para los medios cargados
collections:
  - name: "blog" # Usado en rutas, por ejemplo, /admin/collections/blog
    label: "Blog" # Usado en la interfaz de usuario de /admin
    folder: "src/pages/posts" # La ruta a la carpeta donde se almacenan los documentos
    create: true # Permitir a los usuarios crear nuevos documentos en esta colección
    fields: # Los campos para cada documento, generalmente en el frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "/src/layouts/MarkdownPostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          label_singular: "Añadir categoría",
          field: { label: Tag, name: tag, widget: string },
        }
      - { label: "Body", name: "body", widget: "markdown" }
